framework:
  messenger:
    # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
    # failure_transport: failed

    transports:
      async_outbound:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          queues:
            async_outbound: async_outbound
      async_inbound:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          queues:
            async_inbound: async_inbound

    routing:
      App\Message\OcrMessage: async_outbound
      App\Message\OcrResultMessage: async_inbound
