framework:
  messenger:
    serializer:
      default_serializer: messenger.transport.symfony_serializer
      symfony_serializer:
        format: json
        context: {}

    transports:
      outbound:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          queues:
            async_outbound: async_outbound
          exchange:
            name: outbound
            type: direct

      inbound:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          queues:
            async_inbound: async_inbound
          exchange:
            name: inbound
            type: direct

    routing:
      App\Message\OcrMessage: outbound
      App\Message\OcrResultMessage: inbound