framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            async_outbound:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queues:
                        async_outbound: async_outbound

        routing:
            # Route your messages to the transports
             'App\Message\OcrMessage': async_outbound
